# Use the official Golang image as the base image
FROM golang:1.22.4-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod files and download GO modules
COPY go.mod ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# copy resource code
COPY *.go ./

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o ./go-hello-world

#optional : expose port
EXPOSE 8080

#run
CMD ["./go-hello-world"]